"""Recreate missing migration

Revision ID: 50236e67b0dc
Revises: a3024c55c12e
Create Date: 2024-11-20 02:22:57.046766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50236e67b0dc'
down_revision: Union[str, None] = 'a3024c55c12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('users', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'gain_muscle', 'health_maintenance', name='goalenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'health_conditions',
               existing_type=postgresql.ENUM('diabetes', 'hypertension', 'kidney_disease', 'none', name='healthconditionenum'),
               type_=sa.String(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('users', 'health_conditions',
               existing_type=sa.String(),
               type_=postgresql.ENUM('diabetes', 'hypertension', 'kidney_disease', 'none', name='healthconditionenum'),
               nullable=False)
    op.alter_column('users', 'goal',
               existing_type=sa.String(),
               type_=postgresql.ENUM('lose_weight', 'gain_muscle', 'health_maintenance', name='goalenum'),
               existing_nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('users', 'weight',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
